name: Daily Amazon Deal Poster

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hrs
  workflow_dispatch:

jobs:
  post-deals:
    runs-on: ubuntu-latest
    env:
      FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
      FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the bot
        run: python main.py
